apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-data2
  namespace: monitoring
  labels:
    type: local
    app: prometheus
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp
