apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local-data2
  namespace: monitoring
  labels:
    app: prometheus
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: pv-local-data2